name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
#       - cron: "0 0 */1 * *" # 매일 00시00분에
      - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        # here
        with: 
          python-version: 3.10.7
          cache: pip
          cache-dependency-path: ./requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ./requirements.txt
      - name: Update README.md file
        run: | 
          git pull
          git add .
          git diff
          git config --local user.email "tingstyle1@gmail.com"
          git config --local user.name "is2js"
          git commit -m "update readme.md"
          git push
      - name: Run manage.py
        run: |
          python manage.py
